spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sifu
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat
#  file: /var/log/tomcat/sell.log
#  level: error
#    com.imooc.LoggerTest: debug